[api_keys]
news_api_key = "YOUR_NEWS_API_KEY"
scholar_api_key = "YOUR_SCHOLAR_API_KEY"

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"
